version: 2.1
jobs:
  fsharp-build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run: dotnet tool restore
      - run: dotnet build 


workflows:
  version: 2
  build:
    jobs:
      - fsharp-build-and-test