version: 2.1
jobs:
  build-and-test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run: ls -laR
      - run: cd project
      - run: make deps
      - run: make build
      - run: make test
      - run: make check-format
      - run: make package


workflows:
  version: 2
  build:
    jobs:
      - build-and-test
